apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tokhub.fullname" . }}-secret
  labels:
    {{- include "tokhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  TOKHUB_SECRET_KEY: {{ .Values.secretKey | quote }}
