// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AdminAgentIdempotencyKey struct {
	ID             string
	TokenID        string
	IdempotencyKey string
	Method         string
	Path           string
	CreatedAt      time.Time
}

type AdminAgentToken struct {
	ID          string
	Name        string
	TokenHash   string
	TokenPrefix string
	TokenMask   string
	Scopes      json.RawMessage
	CreatedBy   string
	ExpiresAt   sql.NullTime
	RevokedAt   sql.NullTime
	LastUsedAt  sql.NullTime
	CreatedAt   time.Time
}

type AlertConfigState struct {
	Scope                 string
	OrgID                 string
	DefaultsInitializedAt time.Time
	UpdatedBy             sql.NullString
	UpdatedAt             time.Time
}

type AlertDelivery struct {
	ID                    string
	OrgID                 string
	Scope                 string
	RuleID                sql.NullString
	NotificationChannelID sql.NullString
	IncidentID            sql.NullString
	DedupeKey             string
	Severity              string
	Status                string
	Title                 string
	Message               string
	Error                 string
	Metadata              json.RawMessage
	CreatedAt             time.Time
	SentAt                sql.NullTime
	DeliveredBy           string
}

type AlertRule struct {
	ID            string
	OrgID         string
	Scope         string
	Name          string
	Kind          string
	Severity      string
	Threshold     string
	WindowMinutes int32
	DedupeMinutes int32
	Enabled       bool
	Config        json.RawMessage
	CreatedBy     sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DataOrigin    string
}

type AuditEvent struct {
	ID         string
	ActorType  string
	ActorID    sql.NullString
	Action     string
	ObjectType string
	ObjectID   sql.NullString
	Ip         sql.NullString
	Result     string
	Metadata   json.RawMessage
	CreatedAt  time.Time
}

type AuthSession struct {
	ID          string
	UserID      string
	SessionHash string
	Ip          sql.NullString
	UserAgent   sql.NullString
	ExpiresAt   time.Time
	RevokedAt   sql.NullTime
	CreatedAt   time.Time
}

type Channel struct {
	ID              string
	OwnerType       string
	OwnerID         sql.NullString
	Name            string
	Provider        string
	Type            string
	Model           string
	UpstreamModel   string
	Endpoint        string
	Status          string
	Score           int32
	ProbeDaily      int32
	ProbesUsedToday int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ProbeResetDate  time.Time
	DataOrigin      string
	PublicVisible   bool
	GatewayEnabled  bool
	DisabledAt      sql.NullTime
	DeletedAt       sql.NullTime
	ProviderConfig  json.RawMessage
	OfficialSiteUrl string
	OrgID           sql.NullString
	PublicSlug      string
	IntroTitle      string
	IntroSummary    string
	IntroBody       string
	IntroHighlights json.RawMessage
	LogoUrl         string
	IntroSourceUrl  string
	IntroUpdatedAt  sql.NullTime
}

type ChannelCredential struct {
	ID             string
	ChannelID      string
	OwnerID        string
	KeyCiphertext  string
	KeyNonce       string
	KeyFingerprint string
	KeyMask        string
	Algorithm      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ChannelSite struct {
	ID               string
	Name             string
	Slug             string
	Domain           string
	PublicUrl        string
	RuntimeKeyHash   string
	RuntimeKeyPrefix string
	RuntimeKeyMask   string
	Title            string
	Description      string
	LogoMark         string
	OverviewLabel    string
	RecommendLabel   string
	Modules          json.RawMessage
	CopyJson         json.RawMessage
	SeoJson          json.RawMessage
	QpsLimit         int32
	Status           string
	CreatedBy        sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LastUsedAt       sql.NullTime
	DeletedAt        sql.NullTime
}

type ChannelSiteNavItem struct {
	ID        string
	SiteID    string
	Label     string
	Href      string
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ChannelSitePackageExport struct {
	ID        string
	SiteID    string
	Version   string
	FileName  string
	FileSize  int32
	CreatedBy sql.NullString
	CreatedAt time.Time
}

type ChannelSiteRuntimeLog struct {
	ID         string
	SiteID     sql.NullString
	Endpoint   string
	StatusCode int32
	LatencyMs  int32
	Origin     sql.NullString
	Ip         sql.NullString
	UserAgent  sql.NullString
	CreatedAt  time.Time
}

type ChannelStatusSnapshot struct {
	ID           string
	ChannelID    string
	SampledAt    time.Time
	Status       string
	Score        int32
	Uptime24h    string
	SuccessRate  string
	LatencyP95Ms int32
	L1Status     string
	L2Status     string
	L3Status     string
	L1LatencyMs  int32
	L2LatencyMs  int32
	L3LatencyMs  int32
	TokensUsed   int32
	CostUsd      string
	ErrorType    sql.NullString
	Metadata     json.RawMessage
}

type EmailToken struct {
	ID        string
	UserID    string
	Type      string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type Favorite struct {
	UserID    string
	ChannelID string
	CreatedAt time.Time
}

type Gateway struct {
	ID         string
	OrgID      string
	Name       string
	Slug       string
	BaseUrl    string
	Policy     string
	Status     string
	QpsLimit   int32
	QuotaMonth int32
	CreatedBy  sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DataOrigin string
}

type GatewayKey struct {
	ID            string
	OrgID         string
	GatewayID     string
	Name          string
	KeyHash       string
	KeyPrefix     string
	KeyMask       string
	QuotaMonth    int32
	QpsLimit      int32
	RequestsUsed  int32
	Status        string
	ExpiresAt     sql.NullTime
	LastUsedAt    sql.NullTime
	RevokedAt     sql.NullTime
	CreatedBy     sql.NullString
	CreatedAt     time.Time
	DataOrigin    string
	DeletedAt     sql.NullTime
	KeyCiphertext sql.NullString
	KeyNonce      sql.NullString
}

type GatewayRequestEvent struct {
	ID                string
	GatewayID         string
	GatewayKeyID      sql.NullString
	UpstreamChannelID sql.NullString
	RequestPath       string
	Model             string
	StatusCode        int32
	RequestTokens     int32
	ResponseTokens    int32
	CostUsd           string
	LatencyMs         int32
	ErrorType         sql.NullString
	Stream            bool
	CreatedAt         time.Time
	UsageEstimated    bool
}

type GatewayUpstream struct {
	ID        string
	GatewayID string
	ChannelID string
	Weight    int32
	Priority  int32
	Enabled   bool
	CreatedAt time.Time
}

type Incident struct {
	ID         string
	ChannelID  string
	Status     string
	Title      string
	OpenedAt   time.Time
	ResolvedAt sql.NullTime
	Metadata   json.RawMessage
	DeletedAt  sql.NullTime
}

type IncidentEvent struct {
	ID         string
	IncidentID sql.NullString
	OrgID      string
	EventType  string
	Message    string
	Metadata   json.RawMessage
	CreatedAt  time.Time
}

type ModelCatalog struct {
	ID               string
	Provider         string
	ModelKey         string
	DisplayName      string
	ContextWindow    int32
	CapabilitiesJson json.RawMessage
	Status           string
	CreatedAt        time.Time
}

type ModelPrice struct {
	ID            string
	ModelID       string
	ChannelID     sql.NullString
	InputPerMtok  string
	OutputPerMtok string
	Currency      string
	EffectiveAt   time.Time
}

type NotificationChannel struct {
	ID                string
	OrgID             string
	Scope             string
	Name              string
	Type              string
	Target            string
	Enabled           bool
	CreatedBy         sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DataOrigin        string
	LastTestedAt      sql.NullTime
	LastError         string
	TargetCiphertext  string
	TargetNonce       string
	TargetMask        string
	TargetFingerprint string
	TargetAlgorithm   string
}

type OpenApiCallLog struct {
	ID         string
	SiteID     sql.NullString
	Endpoint   string
	StatusCode int32
	LatencyMs  int32
	Ip         sql.NullString
	UserAgent  sql.NullString
	CreatedAt  time.Time
}

type OpenApiSite struct {
	ID            string
	Name          string
	SiteKeyHash   string
	SiteKeyPrefix string
	SiteKeyMask   string
	Scopes        []string
	QpsLimit      int32
	Status        string
	CreatedBy     sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastUsedAt    sql.NullTime
	DataOrigin    string
	DeletedAt     sql.NullTime
}

type OpsReleaseCheck struct {
	ID        string
	CheckName string
	Scope     string
	Status    string
	Detail    json.RawMessage
	CheckedAt time.Time
}

type Org struct {
	ID                           string
	Name                         string
	Slug                         string
	Plan                         string
	Status                       string
	Timezone                     string
	CreatedAt                    time.Time
	DataOrigin                   string
	DefaultGatewayPolicy         string
	DefaultNotificationChannelID sql.NullString
	UpdatedAt                    time.Time
	SuspendedAt                  sql.NullTime
	DeletedAt                    sql.NullTime
}

type OrgMember struct {
	OrgID     string
	UserID    string
	Role      string
	GroupName sql.NullString
	Status    string
	CreatedAt time.Time
}

type ProbeResult struct {
	ID         string
	ProbeRunID string
	ChannelID  string
	Layer      string
	Step       string
	Status     string
	LatencyMs  int32
	HttpStatus sql.NullInt32
	ErrorType  sql.NullString
	Metadata   json.RawMessage
	CreatedAt  time.Time
}

type ProbeRun struct {
	ID         string
	ChannelID  string
	Layer      string
	Source     string
	Status     string
	StartedAt  time.Time
	FinishedAt sql.NullTime
	ErrorType  sql.NullString
	Metadata   json.RawMessage
}

type RecommendClickEvent struct {
	ID        string
	ItemType  string
	ItemID    string
	ChannelID sql.NullString
	UserID    sql.NullString
	Ip        sql.NullString
	UserAgent sql.NullString
	CreatedAt time.Time
}

type RecommendPick struct {
	ID         string
	ChannelID  string
	Position   int32
	Title      string
	Ribbon     string
	Summary    string
	PointsJson json.RawMessage
	CtaLabel   string
	CtaUrl     string
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DataOrigin string
}

type RecommendRankRule struct {
	ID          string
	Label       string
	Description string
	Metric      string
	Position    int32
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DataOrigin  string
}

type RecommendReward struct {
	ID            string
	ChannelID     sql.NullString
	ProviderName  string
	RewardType    string
	RewardValue   string
	Code          string
	ExpiresAtText string
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DataOrigin    string
}

type RecommendScenario struct {
	ID         string
	Title      string
	Icon       string
	ChannelID  sql.NullString
	Summary    string
	Position   int32
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DataOrigin string
}

type SiteConfig struct {
	Key       string
	ValueJson json.RawMessage
	UpdatedBy sql.NullString
	UpdatedAt time.Time
}

type UsageDailyRollup struct {
	Day          time.Time
	OrgID        string
	Source       string
	GatewayID    string
	ChannelID    string
	Model        string
	MemberUserID string
	Requests     int32
	Tokens       int32
	CostUsd      string
	Errors       int32
	ProbeRuns    int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID              string
	Email           string
	PasswordHash    string
	Name            string
	Avatar          string
	Status          string
	Role            string
	EmailVerifiedAt sql.NullTime
	LastActiveAt    sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DataOrigin      string
	SuspendedAt     sql.NullTime
	DeletedAt       sql.NullTime
	Plan            string
	Username        sql.NullString
}
