// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phase1.sql

package db

import (
	"context"
)

const phaseOneNoop = `-- name: PhaseOneNoop :one
select 1::int as ok
`

func (q *Queries) PhaseOneNoop(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, phaseOneNoop)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
